apiVersion: v1
kind: Service
metadata:
  name: claim-service
spec:
  selector:
    app: claim-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 31002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: claim-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: claim-service
  template:
    metadata:
      labels:
        app: claim-service
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: mysqldb-supermarket
            - name: MYSQL_DATABASE
              value: supermarket_db
            - name: MYSQL_USER
              value: elvara
            - name: MYSQL_PASSWORD
              value: "pass"
          image: elvara/claim-service
          name: claim-service
          ports:
            - name: http
              containerPort: 8080

---